name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Git pull & npm install
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_USER_PASSWORD }}
        script: |
          cd /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}
          git pull
          npm install

    - name: Create .env file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_USER_PASSWORD }}
        script: |
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" > /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}/.env
          echo "SECRET=${{ secrets.SECRET }}" >> /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}/.env
          echo "PORT=${{ secrets.PORT }}" >> /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}/.env