name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Copy code to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_USER_PASSWORD }}
        script: |
          rsync -avz --delete ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}

    - name: Create .env file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_USER_PASSWORD }}
        script: |
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" > /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}/.env
          echo "SECRET=${{ secrets.SECRET }}" >> /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}/.env
          echo "PORT=${{ secrets.PORT }}" >> /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}/.env