name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: 164.90.226.115
        username: elsol
        password: elS2807ol16sn!!
        script: |
          cd /home/${{ secrets.REMOTE_USER }}
          mkdir test